PS D:\60_learning\05_pluralsight\pluralsight_python\organizing-larger-programs> python .\multi-reader-program\
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".\multi-reader-program\__main__.py", line 5, in <module>
    f = MultiReader(sys.argv[1])
IndexError: list index out of range
PS D:\60_learning\05_pluralsight\pluralsight_python\organizing-larger-programs> python .\multi-reader-program\ text.bz2
New Sample compressed with BZ2...
PS D:\60_learning\05_pluralsight\pluralsight_python\organizing-larger-programs> python .\multi-reader-program\ text.gz
New Sample Text compressed with GZIP...
PS D:\60_learning\05_pluralsight\pluralsight_python\organizing-larger-programs> python .\multi-reader-program\ .\multi-reader-program\__main__.py
import sys

from demo_reader.multireader import MultiReader

f = MultiReader(sys.argv[1])
print(f.read())
f.close()
